#139 fixed
hoprnet/myne-chat pull request #141
Opened 2022-06-24 18:46 UTC by aahutsal

Seems I've fixed, @nionis please review

2022-06-27 09:03 UTC, nionis requested changes

2022-07-01 07:50 UTC, aahutsal commented on .gitignore
> +/hoprnet-release-lisbon/
Done.

2022-07-01 07:51 UTC, aahutsal commented on README.md
> +HTTP API=http://localhost:8080/api/v2/r
Sorry, mistype. Fixed.

2022-07-01 07:52 UTC, aahutsal commented on next.config.js
> +const rewrites = () => {
This is used to proxy calls sent to `https://localhost:8080/api/v2/` to `http://<HOPR_NODE_HTTP_URL>/api/v2`.

2022-07-01 07:55 UTC, aahutsal commented on __tests__/index.test.tsx
> -    expect(peerIdElement).toBeInTheDocument()
Because the page content has been changed. There are no elements with `role=button` having text `Add New Conversation` anymore and neither element with `role=textbox`

2022-07-01 11:03 UTC, nionis requested changes
main issue that needs to be resolves is the way the endpoint is set - needs to use query parameters, please check this example https://github.com/hoprnet/hopr-community/blob/0259730b0d36a6c1d9f8773eb01a98cced57a23f/projects/hopr-visual/src/views/Root.tsx#L32

2022-07-01 11:13 UTC, nionis commented
@aahutsal for extra bonus HOPR, could you remove the `cluster` option in the configuration? it's not needed anymore

2022-07-01 13:12 UTC, aahutsal commented
> @aahutsal for extra bonus HOPR, could you remove the `cluster` option in the configuration? it's not needed anymore

Will do.

2022-07-11 17:56 UTC, aahutsal commented on tsconfig.json
> +  "exclude": ["node_modules", "hoprnet-release-lisbon"]
Fixed in e4fa75b62b4ef16d6302e9d08fd049b1dae005d8

2022-07-13 17:42 UTC, aahutsal commented on next.config.js
> +const rewrites = () => {
done

2022-07-13 17:43 UTC, aahutsal commented on README.md
> +HTTP API=http://localhost:8080/api/v2/
done

2022-07-13 17:43 UTC, aahutsal commented on tsconfig.json
> +  "exclude": ["node_modules", "hoprnet-release-lisbon"]
done

2022-07-18 09:44 UTC, nionis commented
hey @aahutsal, when do you think you will be able to complete this PR? From what I see, there are still a few things missing.

1. the use of API v2 WS endpoint (ws://127.0.0.1:3001/api/v2/messages/websocket/?apiToken=myApiToken)
2. removal of cluster option
3. removal of WS endpoint option

In API v2, both rest and WS endpoints are under the same port, see API [here](https://docs.hoprnet.org/developers/rest-api)

2022-07-18 10:20 UTC, aahutsal commented
@nionis Can you check later today?

2022-08-01 08:16 UTC, aahutsal commented
1 and 3 Been implemented in https://github.com/hoprnet/myne-chat/pull/141/commits/ea32785c114ec4fe77917a3c1110e6a43cd28b35 and reverted back in next one. Seems this warning message confused me:

![image](https://user-images.githubusercontent.com/1643117/182104141-d3f1297c-b7e9-4169-932c-582631141271.png)

2. Can't find any `cluster` option. Please, explain. I'm still new to HOPR

2022-08-01 10:04 UTC, nionis approved these changes, later dismissed

2022-08-01 10:04 UTC, nionis commented on src/components/settings.tsx
>      const BASE_HTTP = 'http://localhost:3000'
```suggestion
    const BASE_HTTP = 'http://localhost:3001'
```

2022-08-01 10:04 UTC, nionis commented on src/components/settings.tsx
> +          placeholder="http://localhost:8080/"
```suggestion
          placeholder="http://localhost:3001/"
```

2022-08-01 10:04 UTC, nionis commented on src/stories/Quickstart.stories.mdx
> +    MyneChat: https://8080-hoprnet-mynechat-q0d9mzehwlb.ws-us29.gitpod.io/?httpEndpoint=https://13301-hoprnet-mynechat-q0d9mzehwlb.ws-us29.gitpod.io&wsEndpoint=wss://19501-hoprnet-mynechat-q0d9mzehwl
```suggestion
    MyneChat: https://8080-hoprnet-mynechat-q0d9mzehwlb.ws-us29.gitpod.io/?apiEndpoint=https://13301-hoprnet-mynechat-q0d9mzehwlb.ws-us29.gitpod.io&apiToken=^^LOCAL-testing-123^^
```

2022-08-01 10:06 UTC, nionis commented
hey @aahutsal, HOPR had participated in ETH Paris and also had it's team week so we have been AFK for about 2 weeks, sorry for the delay. Lets merge my suggestions and we can then give the greenlight for @mjadach-iv to review, thanks
I mostly see some inconsistencies but I think I covered them all.

2022-08-01 10:14 UTC, aahutsal commented
> hey @aahutsal, HOPR had participated in ETH Paris and also had it's team week so we have been AFK for about 2 weeks, sorry for the delay. Lets merge my suggestions and we can then give the greenlight for @mjadach-iv to review, thanks
> I mostly see some inconsistencies but I think I covered them all.

Sorry, didn't know that. Congrats! ;)

2022-08-01 14:40 UTC, aahutsal reviewed
`apiEndpoint` should be used in place of `httpEndpoint`

2022-08-03 06:10 UTC, nionis approved these changes

2022-08-03 06:10 UTC, merged

2022-08-03 14:04 UTC, aahutsal commented
@nionis Seems you've merged, that's good. Hopefully, you will release funds soon.

2022-08-03 14:14 UTC, nionis commented
@aahutsal this week, no worries, we have payout plenty of bounties in the past, see https://bounties.hoprnet.org/showcase

2022-08-03 14:36 UTC, aahutsal commented
Trust you man, no worries. Since I'm getting familiar with the api,  I could probably pick one more to complete

2022-08-08 05:59 UTC, aahutsal commented
> @aahutsal for extra bonus HOPR, could you remove the cluster option in the configuration? it's not needed anymore

No extra bonus for `Cluster option removal`? ;)

2022-08-09 13:52 UTC, aahutsal commented
No, nothing in the blockchain:
https://etherscan.io/address/0x7268b488DDeae388C11426B98f521939114bdEa6

2022-08-10 15:19 UTC, thewanderingeditor commented
Should have been clearer. Was sent on Gnosis Chain. This is where most HOPR tokens live, as well as our staking program. We're looking to move gitcoin bounties to Gnosis as well, once support is implemented.

 https://blockscout.com/xdai/mainnet/token/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/token-transfers

2022-08-10 17:14 UTC, aahutsal commented
> 0x7268b488DDeae388C11426B98f521939114bdEa6

Thanks for clarifying, @thewanderingeditor . Hopefully, you didn't send much, as the address provided is my coinbase wallet, thus I don't have access to PKs, and neither does coinbase have it, as it's a custodial service.

2022-08-10 17:35 UTC, thewanderingeditor commented
Ah sorry about that. I should have checked. It wasn't that much, so no great harm done. If you have another address with Gnosis access I can send there, or if you're happy to wait a bit longer we can try again from a mainnet bounty wallet.

2022-08-11 02:28 UTC, aahutsal commented
0x6c7623Eed8fb55dE471B3AfA2f44afcC2e2946d4
This is my MetaMask address on the Gnosis chain.

2022-08-24 17:11 UTC, aahutsal commented
@thewanderingeditor seems you do not read closed pull requests :) Check my message above. It was sent exactly 2 weeks ago.

2023-11-17 15:16 UTC, aahutsal commented
@thewanderingeditor now over a year ago