W/o URI encoded some API tokens will fail
hoprnet/myne-chat pull request #45
Opened 2021-12-18 19:01 UTC by jjperezaguinaga

2021-12-18 19:11 UTC, tolbrino requested changes

2021-12-18 19:11 UTC, tolbrino commented on README.md
> +_Important: Your API token might vary, which means it might have unsupported parameters as query parameters (e.g, `%`, `+`). Because we are passing the API token as query string, your token might nee
```suggestion
_Important: Your API token might vary, which means it might have unsupported parameters as query parameters (e.g, `%`, `+`). Because we are passing the API token as query string, your token might need to be `URIEncoded` for it to work. To be safe, please make sure it's properly [encoded](https://www.onlinewebtoolkit.com/url-encode-decode) before pasting the API token into the UI. This will be improved in future versions of Myne Chat._
```

2021-12-20 18:13 UTC, jjperezaguinaga commented
@tolbrino Added suggestion

2021-12-20 20:30 UTC, tolbrino approved these changes

2021-12-21 11:40 UTC, merged